spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydb"
    username: admin
    password: admin
  database:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
